NAME: 'MDiffuse_1026_newVal_VaeDiffuse_eval_VaeActorLatent1KL1e4_MEncDec66_MdiffEnc48_bs128_clipHidden_uncond75_01' # Experiment name
DEBUG: True # Debug mode
SEED_VALUE: 1234 # Seed value
ACCELERATOR: 'gpu' # Devices optioncal: “cpu”, “gpu”, “tpu”, “ipu”, “hpu”, “mps, “auto”
DEVICE: [0] # Index of gpus eg. [0] or [0,1,2,3]

# Training configuration
TRAIN:
  #---------------------------------
  STAGE: diffusion # stage "vae" or "diffusion", "vae_diffusion"
  # STAGE: vae_diffusion # stage "vae" or "diffusion", "vae_diffusion"
  #---------------------------------
  ABLATION:
    VAE_TYPE: actor # mcross actor
    SKIP_CONNECT: True
    LATENT_SIZE: 1
    IS_DIST: True
    MLP_DIST: True
    NOSTD: False # ablation study for cycle loss
    CYCLE: False # ablation study for cycle loss
  DATASETS: ['humanml3d'] # Training datasets
  NUM_WORKERS: 11 # Number of workers
  BATCH_SIZE: 128 # Size of batches
  START_EPOCH: 0 # Start epochMMOTIONENCODER
  END_EPOCH: 9999999 # End epoch
  RESUME: None # Resume training from this path
  #
  # PRETRAINED_VAE: ''
  # best mcross vae model 
  # PRETRAINED_VAE: /apdcephfs/share_1227775/shingxchen/AIMotion/TMOSTData/exps/mdiffuse/MDiffuse_1022_TrainVaeMcross_Latent5_lossFeatsJointsKL_for_diffuse_unconpipe/checkpoints/epoch=3799.ckpt
  # PRETRAINED_VAE: '/apdcephfs/share_1227775/shingxchen/AIMotion/TMOSTData/exps/mcrossvae/MCROSS_1010_vae_feats_kl_fixcross/checkpoints/epoch=3599.ckpt' # Pretrained model path
  #
  # best mcross vae model 
  # PRETRAINED_VAE: '/apdcephfs/share_1227775/shingxchen/AIMotion/TMOSTData/exps/mcrossvae/MCROSS_1010_vae_feats_kl_fixcross/checkpoints/epoch=3599.ckpt' # Pretrained model path
  #
  # best actor vae model 
  PRETRAINED_VAE: "/apdcephfs/share_1227775/shingxchen/AIMotion/TMOSTData/exps/mdiffuse/MDiffuse_1013_TrainVaeActor_2Metric_humanML3D/checkpoints/epoch=3999.ckpt"
  # PRETRAINED_VAE: /apdcephfs/share_1227775/shingxchen/AIMotion/TMOSTData/exps/mdiffuse/MDiffuse_1022_TrainVaeACTOR_Latent1_lossFeatsJointsKL_for_diffuse_unconpipe/checkpoints/epoch=3799.ckpt
  # PRETRAINED_VAE: /apdcephfs/share_1227775/shingxchen/AIMotion/TMOSTData/exps/mdiffuse/MDiffuse_1020_TrainVaeMcross_Latent5_for_diffuse_unconpipe/checkpoints/epoch=7799.ckpt
  # 
  # default actor vae model
  # PRETRAINED_VAE: /apdcephfs/share_1227775/shingxchen/AIMotion/TMOSTData/exps/actor/ACTOR_1010_vae_feats_kl/checkpoints/epoch=1599.ckpt
  # 
  # PRETRAINED: /apdcephfs/share_1227775/mingzhenzhu/jiangbiao/TMOST/experiments/mdiffuse/MDiffuse_1014_VaeActor_humanML3D_transdec_4dec_clip/checkpoints/epoch=2499.ckpt # Pretrained model path
  PRETRAINED: ''
  OPTIM:
    TYPE: AdamW # Optimizer type
    LR: 1e-4 # Learning rate
    
# Evaluating Configuration
EVAL:
  DATASETS: ['humanml3d'] # Evaluating datasets
  BATCH_SIZE: 32 # Evaluating Batch size
  SPLIT: test

# Test Configuration
TEST:
  CHECKPOINTS: /apdcephfs/share_1227775/mingzhenzhu/jiangbiao/TMOST/experiments/mdiffuse/MDiffuse_1014_VaeActor_humanML3D_transdec/checkpoints/latest-epoch=549.ckpt # Pretrained model path
  DATASETS: ['humanml3d'] # training datasets
  SPLIT: test
  BATCH_SIZE: 32 # training Batch size
  MEAN: False
  NUM_SAMPLES: 1
  FACT: 1

# Datasets Configuration
DATASET:
  JOINT_TYPE: 'humanml3d' # join type
  KIT:
    FRAME_RATE: 20.0 # Frame rate for rendering
    # FRAME_RATE: 12.5 # Frame rate for rendering
    PICK_ONE_TEXT: True # Pick one text when training
METRIC:
  # TYPE: ['TM2TMetrics']
  # TYPE: ['TemosMetric']
  TYPE: ['TemosMetric','TM2TMetrics', 'MRMetrics']
# Losses Configuration
LOSS:
  TYPE: mdiffuse # Losses type
  LAMBDA_LATENT: 1.0e-5 # Lambda for latent Losses
  LAMBDA_KL: 1.0e-4 # Lambda for kl Losses
  LAMBDA_REC: 1.0 # Lambda for reconstruction Losses
  LAMBDA_GEN: 1.0  # Lambda for text-motion generation losses
  LAMBDA_CROSS: 1.0 # Lambda for reconstruction Losses
  LAMBDA_CYCLE: 0.0 # Lambda for cycle Losses
  DIST_SYNC_ON_STEP: False # Sync Losses on step when distributed trained

# Model Configuration
MODEL:
  VAE: True # Whether vae model
  MODEL_TYPE: mdiffuse # Model Type
  LATENT_DIM: [1,256] # Latent dimension
  FF_SIZE: 1024 # 
  NUM_LAYERS: 9 # Number of layers
  NUM_HEAD: 4 # Number of head layers
  DROUPOUT: 0.1 # Dropout rate
  ACTIVATION: gelu # Activation type
  GUIDANCE_SCALE: 7.5
  GUIDANCE_UNCONDP: 0.1
  
  DENOISER:
    TYPE: trans_enc
    # TYPE: trans_dec
  TRANS_DEC:
    NUM_DECODER: 1
  SCHEDULER:
    TYPE: ddim
  TEXT_ENCODER:
    TYPE: clip
    LAST_HIDDEN_STATE: True # for clip
  # Multiplie encoder network
  MOTION_ENCODER:
    TYPE: tmost
    NUM_LAYERS: 6
  MOTION_DECODER:
    NUM_LAYERS: 6
    TYPE: tmost

# Logger configuration
LOGGER:
  SACE_CHECKPOINT_EPOCH: 200
  LOG_EVERY_STEPS: 1
  VAL_EVERY_STEPS: 200
  TENSORBOARD: True
  WANDB:
    PROJECT: mdiffuse
    OFFLINE: False
    RESUME_ID: None
